[WIP] 高度なリクエスト方法を追記する
a11yj/accrefs pull request #53
Opened 2019-09-01 03:23 UTC by oti

#48

2019-09-01 03:57 UTC, oti commented
メモ：INSTALLATION.mdを作る

2019-09-01 07:47 UTC, oti commented
@yuheiy 「より高度なリクエスト方法」向けのドキュメント INSTALLATION.md を追加しました。確認お願いいたします。

2019-09-01 12:20 UTC, yuheiy commented on INSTALLATION.md
> +| `src/index.pug` | トップ |
細かいですが、「ページの種類」で「ホーム」と呼んでいるのでどちらかに合わせた方がよいと思いました。個人的にはどちらかというと「ホーム」と呼ぶ方が好きです。

2019-09-01 12:24 UTC, yuheiy commented on README.md
>  ## より高度なリクエスト方法
「参考資料の追加のみ」みたいな要件でもPRは送ってもいいんですよね？　その是非に依りますが、単にコンテンツを追加するだけでもプルリクエストを送っても良いと取れるような文言があってもいい気がします。

2019-09-01 12:25 UTC, yuheiy requested changes
コメントさせていただきましたー。

2019-09-01 23:01 UTC, oti commented on INSTALLATION.md
> +| `src/index.pug` | トップ |
:wakaru:

2019-09-01 23:36 UTC, oti commented
@yuheiy 

```markdown
リンクの追加や修正、ウェブサイト構成などへの要望は、GitHubのプルリクエストからも受け付けています。

ローカルでの開発手順は[INSTALLATION](INSTALLATION.md)に記載しています。

Patches Welcome!
```

こうしてみました。確認お願いいたします。

2019-09-01 23:36 UTC, oti commented
イシューテンプレートが混ざってますが、これはもう無視してください……:bow:

2019-09-02 03:01 UTC, yuheiy approved these changes
LGTM!

2019-09-02 03:27 UTC, merged