試験的にチートシートのページを作成
a11yj/accrefs pull request #9
Opened 2019-08-22 01:34 UTC by jidaikobo-shibata

こんなかんじ？
- src/md/post/に追加
- src/md/tag/の関連ファイルの編集
だけやってみました。

2019-08-22 02:13 UTC, oti requested changes
@jidaikobo-shibata ありがとうございます！

記事ファイルのYAMLブロックには `link` が必要なので、これは入れてください。

記事に複数リンクがある場合は、プライマリのものが記事タイトルとリンクになっていると良いと思います。

2019-08-22 02:13 UTC, oti commented on src/md/post/チートシート（早見表）.md
> +---
YAML ブロックに `link` キーは必要なので追加お願いします！

本文エリアでリストにしている１つ目のリンクが `link` の値になると良さそうです。

2019-08-23 17:10 UTC, magi1125 approved these changes
よさげ。

2019-08-24 02:27 UTC, oti approved these changes
LGTM!

2019-08-24 02:27 UTC, merged